## Tsyganenko: 

## This model 'reader' uses cloned sources of 
## geopack (https://github.com/tsssss/geopack), 
## geospacepy-lite (https://github.com/lkilcommons/geospacepy-lite), 
## installed using pip install -e ./ in the geopack/ and geospacepy directories, respectively, 
## on top of a python Kamodo environment before starting the jupyter notebook server.
## geospacepy-lite requires the CDF libraries from NASA and spacepy.pycdf to efficiently read OMNI data.


In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

In [3]:
import os.path,datetime

In [4]:
from geopack import geopack

Load IGRF coefficients ...


In [8]:
from kamodo import Kamodo,kamodofy,gridify

ImportError: cannot import name 'gridify' from 'kamodo' (/Users/lrastaet/anaconda3/envs/kamodo37/lib/python3.7/site-packages/kamodo/__init__.py)

### Environmment variable to point to NASA SPDF CDF 
(https://spdf.gsfc.nasa.gov/pub/software/cdf/dist/) installation on your machine

In [6]:
os.environ["CDF_LIB"]='/Applications/cdf/cdf73_1-dist/lib/'

In [7]:
from spacepy import pycdf

In [8]:
import geospacepy

Traceback (most recent call last):
  File "/Users/lrastaet/Desktop_Lutz/Projects/Kamodo/geospacepy-lite/geospacepy/__init__.py", line 8, in <module>
    from geospacepy.geospacepy_config import config
ModuleNotFoundError: No module named 'geospacepy.geospacepy_config'

Solar wind data files will be saved to /Users/lrastaet/Library/Application Support/geospacepy


In [9]:
from tsyganenko import T96,T89,T01,T04

In [10]:
t89_igrf=T89(2010,1,1,10,4,1)

Created interval between 2010-01-01 and 2010-01-01, cadence hourly, start index 10, end index 11
Applying transform Hourly Kp*10 -> Kp to omni hourly variable KP


In [11]:
t89_igrf

T89([(b_x(xvec),
      <function tsyganenko.T89.register_variable.<locals>.interpolate(xvec)>),
     (b_x,
      <function tsyganenko.T89.register_variable.<locals>.interpolate(xvec)>),
     (b_x_ijk(x_i, y_j, z_k),
      <function wrapped(x_i=array([-30.        , -27.89473684, -25.78947368, -23.68421053,
       -21.57894737, -19.47368421, -17.36842105, -15.26315789,
       -13.15789474, -11.05263158,  -8.94736842,  -6.84210526,
        -4.73684211,  -2.63157895,  -0.52631579,   1.57894737,
         3.68421053,   5.78947368,   7.89473684,  10.        ]), y_j=array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ]), z_k=array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ]))>),
     (b_x_ijk,
      <function wrapped(x_i=array([-30.        , -27.89473684, -25.78947368, -23.684210

In [12]:
x=np.array([8.,9.,10.])
y=np.array([0.,1.,2.])
z=np.array([2.,3.,4.])
points=np.column_stack((x,y,z))
points
points[:,0]

array([ 8.,  9., 10.])

In [13]:
t89_igrf.b_x(points)

array([[ 6.22189170e-01],
       [-1.18328788e+03],
       [-2.00080654e+02]])

In [14]:
t89_igrf.detail()

symbol units       lhs   rhs
b_x(xvec)                              b_x(xvec)    nT       b_x  None
b_x_ijk(x_i, y_j, z_k)    b_x_ijk(x_i, y_j, z_k)    nT   b_x_ijk  None
b_y(xvec)                              b_y(xvec)    nT       b_y  None
b_y_ijk(x_i, y_j, z_k)    b_y_ijk(x_i, y_j, z_k)    nT   b_y_ijk  None
b_z(xvec)                              b_z(xvec)    nT       b_z  None
b_z_ijk(x_i, y_j, z_k)    b_z_ijk(x_i, y_j, z_k)    nT   b_z_ijk  None
bvec(xvec)                            bvec(xvec)    nT      bvec  None
bvec_ijk(x_i, y_j, z_k)  bvec_ijk(x_i, y_j, z_k)    nT  bvec_ijk  None

In [15]:
t89_igrf['B_x[T]']='b_x'

In [16]:
t89_igrf.detail()

symbol units       lhs  \
b_x(xvec)                              b_x(xvec)    nT       b_x   
b_x_ijk(x_i, y_j, z_k)    b_x_ijk(x_i, y_j, z_k)    nT   b_x_ijk   
b_y(xvec)                              b_y(xvec)    nT       b_y   
b_y_ijk(x_i, y_j, z_k)    b_y_ijk(x_i, y_j, z_k)    nT   b_y_ijk   
b_z(xvec)                              b_z(xvec)    nT       b_z   
b_z_ijk(x_i, y_j, z_k)    b_z_ijk(x_i, y_j, z_k)    nT   b_z_ijk   
bvec(xvec)                            bvec(xvec)    nT      bvec   
bvec_ijk(x_i, y_j, z_k)  bvec_ijk(x_i, y_j, z_k)    nT  bvec_ijk   
B_x(xvec)                              B_x(xvec)     T       B_x   

                                      rhs  
b_x(xvec)                            None  
b_x_ijk(x_i, y_j, z_k)               None  
b_y(xvec)                            None  
b_y_ijk(x_i, y_j, z_k)               None  
b_z(xvec)                            None  
b_z_ijk(x_i, y_j, z_k)               None  
bvec(xvec)                           None  
bvec_ijk(x_i, y_j, z_k)              None  
B_x(xvec)                1.0e-9*b_x(xvec)

In [17]:
t89_igrf['B_x'](points)

array([[ 6.22189170e-10],
       [-1.18328788e-06],
       [-2.00080654e-07]])

In [18]:
t89_igrf['b_x'](points)

array([[ 6.22189170e-01],
       [-1.18328788e+03],
       [-2.00080654e+02]])

In [19]:
t89_igrf['bvec']((9.,0.,0.))

array([[26.76851212, -0.11158617, 56.98372572]])

In [20]:
t96_igrf=T96(2010,1,1,10,4,1)

Created interval between 2010-01-01 and 2010-01-01, cadence 1min, start index 604, end index 605


In [21]:
t96_igrf.b((xx,yy,zz))

NameError: name 'xx' is not defined

In [ ]:
t01_igrf=T01(2010,1,1,10,4,1)

In [ ]:
t01_igrf.b((xx,yy,zz))

In [ ]:
t04_igrf=T04(2010,1,1,10,4,1)

In [ ]:
t04_igrf